# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stack.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(1068, 831)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setItalic(True)
        StackedWidget.setFont(font)
        StackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.file_page = QtWidgets.QWidget()
        self.file_page.setObjectName("file_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.file_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.browse_button = QtWidgets.QPushButton(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setItalic(True)
        self.browse_button.setFont(font)
        self.browse_button.setObjectName("browse_button")
        self.verticalLayout.addWidget(self.browse_button)
        self.label_4 = QtWidgets.QLabel(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.file_list = QtWidgets.QListWidget(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.file_list.setFont(font)
        self.file_list.setObjectName("file_list")
        self.verticalLayout.addWidget(self.file_list)
        self.search_button = QtWidgets.QPushButton(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.search_button.setFont(font)
        self.search_button.setObjectName("search_button")
        self.verticalLayout.addWidget(self.search_button)
        self.search_bar = QtWidgets.QLineEdit(self.file_page)
        self.search_bar.setText("")
        self.search_bar.setObjectName("search_bar")
        self.verticalLayout.addWidget(self.search_bar)
        self.label_5 = QtWidgets.QLabel(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.file_selected = QtWidgets.QListWidget(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_selected.setFont(font)
        self.file_selected.setObjectName("file_selected")
        self.verticalLayout.addWidget(self.file_selected)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.add_button = QtWidgets.QPushButton(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)
        self.remove_button = QtWidgets.QPushButton(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.remove_button.setFont(font)
        self.remove_button.setObjectName("remove_button")
        self.verticalLayout.addWidget(self.remove_button)
        self.continue_button = QtWidgets.QPushButton(self.file_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.continue_button.setFont(font)
        self.continue_button.setObjectName("continue_button")
        self.verticalLayout.addWidget(self.continue_button)
        StackedWidget.addWidget(self.file_page)
        self.search_menu = QtWidgets.QWidget()
        self.search_menu.setObjectName("search_menu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.search_menu)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title_3 = QtWidgets.QLabel(self.search_menu)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setItalic(True)
        self.title_3.setFont(font)
        self.title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_3.setObjectName("title_3")
        self.gridLayout_3.addWidget(self.title_3, 0, 0, 1, 1)
        self.motif_button = QtWidgets.QPushButton(self.search_menu)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.motif_button.setFont(font)
        self.motif_button.setObjectName("motif_button")
        self.gridLayout_3.addWidget(self.motif_button, 3, 0, 1, 1)
        self.remove_search_button = QtWidgets.QPushButton(self.search_menu)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.remove_search_button.setFont(font)
        self.remove_search_button.setObjectName("remove_search_button")
        self.gridLayout_3.addWidget(self.remove_search_button, 6, 0, 1, 1)
        self.psi_button = QtWidgets.QPushButton(self.search_menu)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.psi_button.setFont(font)
        self.psi_button.setObjectName("psi_button")
        self.gridLayout_3.addWidget(self.psi_button, 4, 0, 1, 1)
        self.hmm_button = QtWidgets.QPushButton(self.search_menu)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.hmm_button.setFont(font)
        self.hmm_button.setObjectName("hmm_button")
        self.gridLayout_3.addWidget(self.hmm_button, 2, 0, 1, 1)
        self.search_genomes_button = QtWidgets.QPushButton(self.search_menu)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.search_genomes_button.setFont(font)
        self.search_genomes_button.setObjectName("search_genomes_button")
        self.gridLayout_3.addWidget(self.search_genomes_button, 7, 0, 1, 1)
        self.to_be_searched = QtWidgets.QListWidget(self.search_menu)
        self.to_be_searched.setObjectName("to_be_searched")
        self.gridLayout_3.addWidget(self.to_be_searched, 1, 0, 1, 1)
        StackedWidget.addWidget(self.search_menu)
        self.patric_page = QtWidgets.QWidget()
        self.patric_page.setObjectName("patric_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.patric_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_patric_button = QtWidgets.QPushButton(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.add_patric_button.setFont(font)
        self.add_patric_button.setObjectName("add_patric_button")
        self.gridLayout_2.addWidget(self.add_patric_button, 7, 0, 1, 2)
        self.name_search_button = QtWidgets.QPushButton(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.name_search_button.setFont(font)
        self.name_search_button.setObjectName("name_search_button")
        self.gridLayout_2.addWidget(self.name_search_button, 4, 0, 1, 1)
        self.continue_button_2 = QtWidgets.QPushButton(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.continue_button_2.setFont(font)
        self.continue_button_2.setObjectName("continue_button_2")
        self.gridLayout_2.addWidget(self.continue_button_2, 9, 0, 1, 2)
        self.patric_remove_button = QtWidgets.QPushButton(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.patric_remove_button.setFont(font)
        self.patric_remove_button.setObjectName("patric_remove_button")
        self.gridLayout_2.addWidget(self.patric_remove_button, 8, 0, 1, 2)
        self.taxon_search_button = QtWidgets.QPushButton(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.taxon_search_button.setFont(font)
        self.taxon_search_button.setObjectName("taxon_search_button")
        self.gridLayout_2.addWidget(self.taxon_search_button, 4, 1, 1, 1)
        self.patric_search = QtWidgets.QLineEdit(self.patric_page)
        self.patric_search.setText("")
        self.patric_search.setObjectName("patric_search")
        self.gridLayout_2.addWidget(self.patric_search, 3, 0, 1, 2)
        self.title_2 = QtWidgets.QLabel(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_2.setFont(font)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.gridLayout_2.addWidget(self.title_2, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 2)
        self.patric_list = QtWidgets.QListWidget(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.patric_list.setFont(font)
        self.patric_list.setObjectName("patric_list")
        self.gridLayout_2.addWidget(self.patric_list, 2, 0, 1, 2)
        self.patric_selected = QtWidgets.QListWidget(self.patric_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patric_selected.setFont(font)
        self.patric_selected.setObjectName("patric_selected")
        self.gridLayout_2.addWidget(self.patric_selected, 6, 0, 1, 2)
        StackedWidget.addWidget(self.patric_page)
        self.start = QtWidgets.QWidget()
        self.start.setObjectName("start")
        self.gridLayout = QtWidgets.QGridLayout(self.start)
        self.gridLayout.setObjectName("gridLayout")
        self.patric_button = QtWidgets.QPushButton(self.start)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.patric_button.setFont(font)
        self.patric_button.setObjectName("patric_button")
        self.gridLayout.addWidget(self.patric_button, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.start)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.fasta_button = QtWidgets.QPushButton(self.start)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.fasta_button.setFont(font)
        self.fasta_button.setObjectName("fasta_button")
        self.gridLayout.addWidget(self.fasta_button, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.start)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        StackedWidget.addWidget(self.start)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.title.setText(_translate("StackedWidget", "Load Data from File"))
        self.browse_button.setText(_translate("StackedWidget", "Browse"))
        self.label_4.setText(_translate("StackedWidget", "Genomes found in file"))
        self.search_button.setText(_translate("StackedWidget", "Search"))
        self.label_5.setText(_translate("StackedWidget", "Selected Genomes"))
        self.add_button.setText(_translate("StackedWidget", "Add"))
        self.remove_button.setText(_translate("StackedWidget", "Remove"))
        self.continue_button.setText(_translate("StackedWidget", "Continue"))
        self.title_3.setText(_translate("StackedWidget", "Search Genomes"))
        self.motif_button.setText(_translate("StackedWidget", "Add Motif Search"))
        self.remove_search_button.setText(_translate("StackedWidget", "Remove"))
        self.psi_button.setText(_translate("StackedWidget", "Add PSI-BLAST Search"))
        self.hmm_button.setText(_translate("StackedWidget", "Add HMM Search"))
        self.search_genomes_button.setText(_translate("StackedWidget", "Search Genomes"))
        self.add_patric_button.setText(_translate("StackedWidget", "Add"))
        self.name_search_button.setText(_translate("StackedWidget", "Search by Name"))
        self.continue_button_2.setText(_translate("StackedWidget", "Continue"))
        self.patric_remove_button.setText(_translate("StackedWidget", "Remove"))
        self.taxon_search_button.setText(_translate("StackedWidget", "Search by Taxon ID"))
        self.title_2.setText(_translate("StackedWidget", "Load Data from PATRIC"))
        self.label_3.setText(_translate("StackedWidget", "Genomes found in PATRIC"))
        self.label_7.setText(_translate("StackedWidget", "Selected Genomes"))
        self.patric_button.setText(_translate("StackedWidget", "PATRIC"))
        self.label_2.setText(_translate("StackedWidget", "Choose a source for genome data."))
        self.fasta_button.setText(_translate("StackedWidget", "FASTA file"))
        self.label.setText(_translate("StackedWidget", "Welcome to the Genome Search Tool 1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StackedWidget = QtWidgets.QStackedWidget()
    ui = Ui_StackedWidget()
    ui.setupUi(StackedWidget)
    StackedWidget.show()
    sys.exit(app.exec_())

